---

#############################################################################
##
##  Auto-Ozmeka
##  T McIntyre for UTS EResearch 2015-2016
##
#############################################################################


- hosts: all
  user: vagrant
  become: yes
  roles:
    - prep
    - apache
    - mariadb
    - omeka-core
    - omeka-plugins
    - omeka-theme
    - solr
